spring.application.name=banking_backend
server.port= 5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false